name: Deploy API to VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish Project
      run: dotnet publish ./Payments_core/Payments_core.csproj -c Release -o publish

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install sshpass -y

    - name: Upload to VPS
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no -r publish/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/c:/deploy/publish/

    - name: Run Deploy Script
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "powershell -ExecutionPolicy Bypass -File C:\deploy\deploy.ps1"